---
- hosts: localhost
  become: yes
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: latest
      when: docker_installed is failed

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_installed
      ignore_errors: yes

    - name: Install Docker Compose if not present
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
      when: docker_compose_installed is failed

    - name: Clone the repository for local development
      git:
        repo: 'https://github.com/qfranklin/app.git'
        dest: .
        version: main
      when: inventory_hostname == 'localhost'

    - name: Build and run the Docker containers for local development
      command: docker-compose up --build
      args:
        chdir: .
      when: inventory_hostname == 'localhost'

- hosts: ec2_instance
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Clone the repository for deployment
      git:
        repo: 'https://your-repository-url.git'
        dest: /path/to/your/app
        version: main

    - name: Deploy with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /path/to/your/app
